---
title: "EDS 223 Week 1 Lab"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
install.packages("sf") # vector data
install.packages("stars") #raster data
install.packages("tmap")
```

```{r}
library(sf) # for vector data 
library(stars) # for raster data 
library(tmap) # for static and interactive maps
library(here)

```


```{r}
# raster of global elevation
world_elevation <- read_stars(here("data", "worldelevation.tif"))
```


```{r}
#country boundaries
world_vector <- read_sf(here("data","worldvector.gpkg"))
```


```{r}
# major cities 
world_cities <- read_sf(here("data", "worldcities.gpkg"))
```

```{r}


 tm_shape(world_elevation, bbox = world_cities) +
  tm_raster() +
tm_shape(world_vector) +
  tm_borders() 

  tm_shape(world_elevation, bbox = c(-15, 35, 45, 65)) +
  tm_raster() +
tm_shape(world_vector) +
  tm_borders() 

  
```



```{r}
tm_shape(world_vector) +
  tm_polygons(col = "lightblue",
              border.col = "black",
              lwd = 0.5, #line width
              lty = "dashed")  #line type
  

```


```{r}
tm_shape(world_vector) +
  tm_borders(col = "red")
  
```

```{r}
tm_shape(world_vector) +
  tm_fill(col = "lightblue")
```

```{r}
tm_shape(world_vector) +
  tm_fill("CO2_emissions")


```



```{r}
tm_shape(world_cities) +
  tm_squares()


```

```{r}
tm_shape(world_vector) +
  tm_polygons("life_expectancy", 
              palette = c("yellow", "darkgreen"),
              title = "Life Expectancy (years)")
```


```{r}
install.packages("viridisLite")
library(viridisLite)
```

```{r}
tm_shape(world_vector) +
  tm_polygons("life_expectancy",
              palette = viridis(option = "plasma", 8),
              title = "Life Expectancy (years)")
```


```{r}
tm_shape(world_vector) +
  tm_polygons() +
  tm_shape(world_cities) +
  tm_symbols(size = "pop2020",
             legend.size.is.portrait = TRUE)


```


```{r}
tm_shape(world_vector) +
   tm_graticules() +
  tm_fill() 
 
```


```{r}

tm_shape(world_vector) +
  tm_fill() +
  tm_scale_bar() +
  tm_compass(position = c("left", "top"))

```

```{r}
tmap_mode("view")

tm_shape(world_vector) +
  tm_fill(col = "wb_income_region",
          palette = viridisLite::plasma(5),
          title = "regional income") +
  tm_layout(bg.color = "lightblue",
            main.title = "Global income by country",
            frame = FALSE)

```

```{r}

tmap_mode("plot")

map1 <- tm_shape(world_vector) +
  tm_fill(col = "wb_income_region",
          palette = viridisLite::plasma(5),
          title = "regional income") +
  tm_layout(bg.color = "lightblue",
            main.title = "Global income by country",
            frame = FALSE)

tmap_save(map1, here("tmap-example.png"))
```

